dist: bionic
language: cpp
before_install:
  - sudo apt-get install libgtest-dev cmake libsdl2-dev
install:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ./unitTest